### ISSUE TITLE
Whacky and broken transitions. Elements not being removed from dom, added too soon.

### ISSUE THREAD

**Issue by JonDum** [ractivejs/ractive#2463]
Hover over and out of each box quickly and watch the magic happen. :dancer: 

http://jsfiddle.net/d3y75cup/

```html
  <div class='root' on-hover='hoverA'>
      Hover over me (nothing fancy)
      
      <div class='items'>
        {{#itemsA}}
            <div class='item' intro-outro='fly'>
                {{.}}
            </div>
        {{/}}
       </div>
  </div>
  
  <div class='root' on-hover='hoverB'>
      Hover over me (fancy)
      
      <div class='items'>
        {{#itemsB:i}}
            <div class='item'
                 intro='fly:{delay: {{ i*100 }}, x: 0, y: {{i*50}} }'
                 outro='fly:{delay: {{ i*100 }} x: 0, y: -50}'>
                {{.}}
            </div>
        {{/}}
       </div>
  </div>
```
```js
var ractive = new Ractive({
  el: 'main',
  template: '#template',
  computed: {
  	itemsA() {
    	var open = this.get('hoveringA');
        if(open)
            return this.get('things');
    },
  	itemsB() {
    	var open = this.get('hoveringB');
        if(open)
            return this.get('things');
    }
  },
  data: {
      things: ["one", "two", "three", "four", "five"],
  },
  oninit() {
  
  	this.on('hoverA', event => {
       this.set("hoveringA", event.hover)
    });
    
  	this.on('hoverB', event => {
       this.set("hoveringB", event.hover)
    });
  }
});
```

**Comment by evs-chris** [comment]
...oh my... :laughing: 

On the plus side, I can only seem to get one extra set of elements stuck in the DOM. Looks like perhaps the cancelled transitions aren't getting their nodes detached in all circumstances.

**Comment by martypdx** [comment]
I found some transition bugs that I fixed as part of #2167, basically it wasn't working correctly when same property would be transitioned prior to previous transition being completed (sounds like this case).

I'd like to get the PR merged anyway, so maybe that would be good first step.

**Comment by Rich-Harris** [comment]
Now that #2167 has been merged I can't get DOM nodes to stick around past their use-by date... does that qualify as 'fixed' in this case? :grin:

**Comment by evs-chris** [comment]
I'm gonna go with "fixed as long as the browser doesn't drop a transition even anywhere?" :smile:

**Comment by JonDum** [comment]
@evs-chris I still see the same behavior :(

Couple seconds playing mousing over and out quickly and I get orphaned nodes.

**Comment by evs-chris** [comment]
Well dang. Perhaps my machine isn't fast enough to get them stuck. I'll play with it some more and see what shakes out.

**Comment by martypdx** [comment]
@evs-chris something to be aware of: a `transitionEnd` event __won't fire__ if the value being assigned is not different than the current value. So we may need to check before attempting transition.

**Comment by heavyk** [comment]
when I get the orphaned nodes, the elements fly in from the wrong direction. normally, they come in from the bottom and leave to the left, but when the orphaned nodes happen, they fly in from the left and then get stuck. I think what's happening is the intro and outro are running are swapping places

**Comment by evs-chris** [comment]
@martypdx I'm not very familiar with the transition code, but it looks like we're already excluding same-valued styles in `animateStyle` here?: https://github.com/ractivejs/ractive/blob/dev/src/view/items/element/Transition.js#L96

My test transition doesn't seem to want to hang, but it just transitions opacity for ease of watching. My next attempt was going to be to wrap the css transition section of `animateStyle` in a setTimeout (cures all, amirite) of delay + duration + 10 to catch the transitionEnd not firing. Or maybe wrap the whole transition in a setTimeout with some default value that the transition can override. The former sounds like a better shot at this, but the latter would perhaps better protect against misbehaving transitions.

**Comment by martypdx** [comment]
> @martypdx I'm not very familiar with the transition code, but it looks like we're already excluding same-valued styles in animateStyle here?:

yes, must be something else (or somewhere else) :(

A cleanup function sounds like a good safety net until we can track down the issue...

**Comment by JonDum** [comment]
@evs-chris fixed with #2585 !
