### ISSUE TITLE
proxy events, method calls and DOM events

### ISSUE THREAD

**Issue by dagnelies** [ractivejs/ractive#2802]
In the old days, you wrote:

```
<button onclick="doSomething( 123 )">...
```

---

Let us replace the 123 by a data item named `foo`. In Ractive, you can now do it using...

**1. Method calls:**
```
var r = new Ractive({
 template: '<button on-click="@this.doSomething( foo )">...',
 doSomething: function(n){...}
}
```

**2. Proxy events:**
```
var r = new Ractive({
 template: '<button on-click="doSomething:{{foo}}">...',
 oninit: function() {
   this.on( 'doSomething', function (event, n) {...} );
  }
}
```

**3. The DOM way:**
```
function doSomething(n){...};

var r = new Ractive({
 template: '<button onclick="doSomething({{foo}})">...'
}
```

----

Now I don't know what you think, but I always found it pretty ...hmm ...non-intuitive. Moreover, each way has its own drawbacks.

For 1 (method calls), ~~you can't pass the "event" (that means you can't do something like `event.stopPropagation()` or `event.target`, etc.)~~ ...but it still has a *slightly* unintuitive syntax/semantic IMHO.

For 2 (proxy events), it's a bit cumbersome with unusual syntax, and you can't call Ractive functions like `set(...)`

For 3 (DOM events), you can't pass objects (they'll be interpolated as the string "[Object]"), and it can't meaningfully work inside components

...each one is sucky in its own way so that you may have to use a mix of those depending on your app.

---

**So what do you think of this...**

Since I basically want it to be as simple as possible, and as intuitive as possible, I'd like to stick to the DOM related way. I would like to suggest two slight improvements how DOM handlers are handled which could make a big difference.

First, don't interpolate {{mustaches}} in `on...` handlers using `toString` but by JSON stringifying them. That way, handlers like this are possible:
```
<button onclick="doSomething(event, {{bar}})">... (where {{bar}} is an object)
```

The other, probably more tricky, is to make it components compatible:
```
<button onclick="@this.componentFunction(event, {{bar}})">
```
Which should call the `componentFunction` of the component ...or the Ractive instance if it's in a normal template.

IMHO this would be a fully intuitive, simple, almost zero learning curve approach, while removing the drawbacks of '1' and '2', to the point of making both obsolete.

What do you think?

**Comment by ghost** [comment]
Soo...

> Method calls

This is the way to go at the moment, write like regular inline JavaScript. You also have the `@` prefixes at your disposal. The event object, as far as I remember, is accessible via `this.event` in the method or `@this.event` in the template. 

> Proxy events

Proxy events arguments is being deprecated in 0.8 and is removed in edge.

> The DOM way

This just renders like a regular element with a non-Ractive attribute (which happens to be a DOM event attribute) with an interpolated value.

The concern is probably less related to the event and handling, but more of the serialization of the data. This _might_ be tricky since you need to account for the double quotes. Possible, but maybe tricky.

> `<button onclick="@this.componentFunction(event, {{bar}})">`

This will just render the following in the DOM since `onclick` isn't a Ractive directive and treats it as a regular attribute:

```
<button onclick="@this.componentFunction(event, [object Object])">
```

If you meant the following (`on-click`), this would throw as it would be invalid syntax.

```
<button on-click="@this.componentFunction(event, {{bar}})">
```

The Right Way™ which works today is to just omit the mustache.

```
<button on-click="@this.componentFunction(event, bar)">
```

**Comment by evs-chris** [comment]
With edge, method events are possible unprefixed by default and with a shorthand prefix. Also, the DOM event is available to method events as `event.original`:

`<button on-click="doSomething(event.original, bar)">` - calls the Ractive method `doSomething` with the DOM event and the `bar` object. The unambiguous form is 
`<button on-click="@.doSomething(event.original, bar)">`.

As far as inline event listeners, I believe they have to be global, so the `doSomething` wouldn't be on the Ractive instance, would it?

**Comment by dagnelies** [comment]
I indeed missed the fact that you can now pass events to method calls, that's cool, I corrected the statement in the initial post.

Before I go on, I would like to point out a very important point regarding the statement:

> proxy events are meant to be deprecated and method calls the way to go

Well, that is the developer's state and I'm aware of it too. **However the tutorials and the docs still point to proxy events as the "way to go"!** The official tutorial even *only* presents proxy events, while in the help, method calls are merely presented as an alternative to proxy events. I'll see if I can make up a commit.

---

I'm also aware of what you mentioned in your comments. However, I stick to the statement that the most intuitive syntax for events would be the DOM related I mentioned.

I know it's not how things work currently, nor how it's meant to be used. This talk is purely from a syntax perspective, in the shoes of a noob, ignoring the current state of affairs. That's why I wouldn't label this *question*, but rather *enhancement*.

There are a few intuition pitfalls in the current `on-click`:

1. (Assuming that unqualified event method calls are deprecated) you have to add `@this`, `@global` or some other undocumented `@...` I don't know of.

2. (Assuming unqualified method calls are authorized), `on-click` defaults to the instance while `onclick` defaults to global scope.

3. You don't have to escape parameters ...while they are escaped everywhere else in templates.

...in other words, it differs in several points of what you'd expect, and you can't guess it until you've crawled through the docs.

---

That's why I think that, in the long term, the initially suggested syntax/mechanic would be the most intuitive:

```
<button onclick="doSomething( {{bar}} )"> // resolving to global scope like normal DOM event
<button onclick="@this.doSomething( {{bar}} )">  // resolving to instance scope
```

This is simply how one would expect things to work.

PS: ...but I'm aware such a change would probably be a big deal since it's at the core of Ractive.

**Comment by ghost** [comment]
> However the tutorials and the docs still point to proxy events as the "way to go"!

@evs-chris mentioned somewhere that he's working on a revamp of docs so that might change in the near future. 😄 

> you have to add `@this`, `@global` or some other undocumented `@`... I don't know of.

There's documentation for the `@` things actually. It's in [References](http://docs.ractivejs.org/latest/references), but at the bottom of the page.

---

Hooking on to regular DOM event attributes might be a big deal. There _might_ be a legitimate uses for having them stay as is (which I don't know of, other users might have).

It would also make it a bit confusing from a different angle: Ractive appears to be "intercepting" DOM event attributes for its events use. It's a whole new world of documentation.

It also would make it a bit confusing determining from first glance which things are for Ractive and which aren't. Currently, we have `on-*`, `as-*`, `*-in`, `*-out`, and`*-in-out` which are pretty good at indicating Ractive's special things (though I prefer much more verbose versions).

**Comment by tomekmarchi** [comment]
Proxy events are my go to and is the only form that I consider good practice. However, method calls are still used just much less and for specific situations. A grand total of 1 times.

**Comment by evs-chris** [comment]
The reason that proxy events with arguments got deprecated is it's very difficult to tell what will _actually_ happen with their args based on what you see. There are some cases where you think you would have multiple args passed, but what you _actually_ get is a single string arg with you args interpolated into it.

We still have a bit of unfortunate inconsistency in attribute templates regarding what requires mustaches and what doesn't. I'd like to get to the point that all directives (things that ractive expects to provide a potentially non-string value) don't require (interpolator) mustaches, which imply that there's some sort of string substitution happening. We _could_ adjust things to do string substitution and `eval`, but that would kill csp.

Regarding `<button onclick="doSomething({{ thing }})">`, that would _require_ `eval`, because `doSomething(` is just a string to ractive in that context. Based on the examples, to remain consistent, you would need to use `<button onclick="{{ doSomething(thing) }}">`. Again, I'd like to move toward making directives consistently parse in a data context rather than a string context, meaning that no mustaches are required in the data context because interpolator mustaches imply string context.

I _would_ like to come up with a way to make proxy events with args work out, and I'm starting to think the solution may be to stop using the `on-` directive for two different kinds of events. Perhaps we should move proxies to `proxy-` so that it can have a separate parsing mode that makes sense for proxy events. That would dovetail nicely with syntax to support delegated events using something like `<div delegate-target-click>{{#each ginormousList}}<div delegate-click="doSomething()">...</div>{{/each}}</div>` because when you get over about 100 elements you start seeing a fair amount of time dedicated to attaching event listeners. That's another topic though.

Finally, I'm going to ping this to #2810, as I think resolving that will make events a fair amount more ergonomic.
